# Generated by Django 2.1.4 on 2018-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collected_at',
            field=models.DateField(),
        ),
    ]
