# Generated by Django 2.1.4 on 2018-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181212_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
