# Generated by Django 2.1.4 on 2018-12-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181213_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
